# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38d3b89971f9e5c91f178d882da386137c618b3fff1fd91b0162193bb0ce876c8219b9409c78c86a99244a1e3630c72b4238240d2b18441754611a0f16c14474

test:
  secret_key_base: 8a33fe953866968ad349be424b62f13190e1131df3660b367292719bbff02b40e9231bc7fc5cde8a40400b5e3368f7fbf62bfc126152d6885d2312e483ce2389

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
